# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
     - master
  pull_request:
    types:
      - opened
      - synchronize

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-customer-api:
    name: Deploy Customer API to Gateway and Dev Portal
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
      - name: Backup Insomnia Spec
        run: |
          mkdir ./spec-backup
          cp ./.insomnia/ApiSpec/*.yml ./spec-backup
          ls ./spec-backup            
      #Installing the inso, deck and portal cli
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install Deck  
        run: |
          curl -sL https://github.com/kong/deck/releases/download/v1.15.0/deck_1.15.0_linux_amd64.tar.gz -o deck.tar.gz
          tar -xf deck.tar.gz -C /tmp
          sudo cp /tmp/deck /usr/local/bin/ 
      - name: Install inso
        run: npm install -g insomnia-inso
   
      # Push Dev Portal changes
      - name: Dev Portal change
        run: |
          curl -X 'PATCH' 'https://us.api.konghq.com/konnect-api/api/portals/${{ secrets.PORTAL_ID }}' \
          -H 'authorization: Bearer ${{ secrets.KONNECT_TOKEN }}' \
          -H 'content-type: application/json' \
          -d @./portal/spec.json
        
      # API Spec linting
      - name: Validate specification
        run: inso lint spec test_Siemens_Swagger
      
      # Prepare OAS spec             
      - name: Prepare URL 4 Declarative Services
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '${'
          tokenSuffix: '}$'
          files: '["./.insomnia/ApiSpec/*.yml"]'
        env:
          UPSTREAM_SERVER_URL: '${{ secrets.UPSTREAM_SERVER_URL }}'
      
      # Generate declarative config
      - name: Generate declarative config
        run: |
          inso generate config test_Siemens_Swagger --tags test_Siemens_Swagger --output kong.yaml
          deck convert --from kong-gateway-2.x --to kong-gateway-3.x --input-file kong.yaml --output-file konnect.yaml
          cat konnect.yaml
      # Ping the Kong instance
      # Sync to Konnect
      - name: Update Kong
        run: deck ping --konnect-token "${{ secrets.KONNECT_TOKEN }}" --konnect-addr "${{ secrets.KONNECT_ADDR }}" && deck sync --konnect-token "${{ secrets.KONNECT_TOKEN }}" --konnect-addr "${{ secrets.KONNECT_ADDR }}" -s konnect.yaml > sync.output.txt
            
      # Run tests
      - name: Run test suites
        run: inso run test test_Siemens_Swagger -e ${{ env.TARGET_ENVIRONMENT }}
        env:
          TARGET_ENVIRONMENT: AntoineEnv
